### ISSUE TITLE
诗画浦江16号rsa那块报错

### ISSUE THREAD

**Issue by zjk2017** [xiaobu689/HhhhScripts#13]
======== ▷ 第 1 个账号 ◁ ========
API请求失败，请检查网络重试: 504
Traceback (most recent call last):
  File "/ql/data/scripts/xiaobu689_HhhhScripts/reads/诗画浦江/诗画浦江.py", line 415, in <module>
    SHPJ(token).main()
  File "/ql/data/scripts/xiaobu689_HhhhScripts/reads/诗画浦江/诗画浦江.py", line 389, in main
    self.credential_auth()
  File "/ql/data/scripts/xiaobu689_HhhhScripts/reads/诗画浦江/诗画浦江.py", line 371, in credential_auth
    body = f"client_id=12&password={quote(rsa_pwd)}&phone_number={self.mobile}"
  File "/usr/local/lib/python3.10/urllib/parse.py", line 881, in quote
    return quote_from_bytes(string, safe)
  File "/usr/local/lib/python3.10/urllib/parse.py", line 906, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

## 执行结束... 2024-09-16 15:21:04  耗时 64 秒

**Comment by xiaobu689** [comment]
> 提交pr了

已合并
