### ISSUE TITLE
人保养鸡报错 

### ISSUE THREAD

**Issue by zjk2017** [xiaobu689/HhhhScripts#16]
## 开始执行... 2024-09-20 20:56:39

xxxxxxxxxxxx

======== ▷ 云养小鸡 ◁ ========
🐔鸡场登录成功
Traceback (most recent call last):
  File "/ql/data/scripts/xiaobu689_HhhhScripts/scripts/中国人保/中国人保【养鸡】.py", line 372, in <module>
    RUN(user_id).main()
  File "/ql/data/scripts/xiaobu689_HhhhScripts/scripts/中国人保/中国人保【养鸡】.py", line 327, in main
    self.daily_sign()
  File "/ql/data/scripts/xiaobu689_HhhhScripts/scripts/中国人保/中国人保【养鸡】.py", line 174, in daily_sign
    if response_json['code'] == 200:
KeyError: 'code'

## 执行结束... 2024-09-20 20:56:51  耗时 12 秒　　

已提交pr 连续签到由get变成post

**Comment by xiaobu689** [comment]
> ## 开始执行... 2024-09-20 20:56:39
> xxxxxxxxxxxx
> 
> ======== ▷ 云养小鸡 ◁ ======== 🐔鸡场登录成功 Traceback (most recent call last): File "/ql/data/scripts/xiaobu689_HhhhScripts/scripts/中国人保/中国人保【养鸡】.py", line 372, in RUN(user_id).main() File "/ql/data/scripts/xiaobu689_HhhhScripts/scripts/中国人保/中国人保【养鸡】.py", line 327, in main self.daily_sign() File "/ql/data/scripts/xiaobu689_HhhhScripts/scripts/中国人保/中国人保【养鸡】.py", line 174, in daily_sign if response_json['code'] == 200: KeyError: 'code'
> 
> ## 执行结束... 2024-09-20 20:56:51 耗时 12 秒　　
> 已提交pr 连续签到由get变成post

okok，已合并
