### ISSUE TITLE
能建个群聊吗？

### ISSUE THREAD

**Issue by ZhangQing3411** [xiaobu689/HhhhScripts#7]
大佬！脚本更新后好多错误不知道怎么改，
Traceback (most recent call last):
  File "/ql/data/scripts/xiaobu689_HhhhScripts_main/上海徐汇.py", line 18, in <module>
    from common import qianwen_messages, make_request, save_result_to_file
ImportError: cannot import name 'qianwen_messages' from 'common' (/ql/data/scripts/xiaobu689_HhhhScripts_main/common.py)
建个群聊吧

**Comment by xiaobu689** [comment]
> 大佬！脚本更新后好多错误不知道怎么改， Traceback (most recent call last): File "/ql/data/scripts/xiaobu689_HhhhScripts_main/上海徐汇.py", line 18, in from common import qianwen_messages, make_request, save_result_to_file ImportError: cannot import name 'qianwen_messages' from 'common' (/ql/data/scripts/xiaobu689_HhhhScripts_main/common.py) 建个群聊吧

已更新，你更新下common.py就可以了，其他不用动

**Comment by liuyang178** [comment]
建个tg群呗
